### ISSUE TITLE
Silicon 1 and Graphite 2 aren't working anymore. 

### ISSUE THREAD

**Issue by Kaank2006** [TheSlaylord/Basic-Schematics#2]
It seems like the 2 of your schematics aren't working (and maybe plastanium 2 too, but that may just be me using it incorrectly.), maybe due to a behaviour change of the underflow gate? (V6)

**Comment by Slotterleet** [comment]
Yeah, snek is fixed, ~~but nobody cares about this mod~~. If I find some time, I'll make more schematics for this.
